<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerLAWadsx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerLAWadsx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerLAWadsx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerLAWadsx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerLAWadsx\App_KernelDevDebugContainer([
    'container.build_hash' => 'LAWadsx',
    'container.build_id' => '93e023d5',
    'container.build_time' => 1716568753,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerLAWadsx');
