<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerH0Kt5wB\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerH0Kt5wB/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerH0Kt5wB.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerH0Kt5wB\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerH0Kt5wB\App_KernelDevDebugContainer([
    'container.build_hash' => 'H0Kt5wB',
    'container.build_id' => 'c0b2ff19',
    'container.build_time' => 1716673101,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerH0Kt5wB');
